# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IO-File-String
version:      0.10
version_from: String.pm
installdirs:  site
requires:
    Test::Easy:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
